import { Link } from "react-router-dom";
import { Check, X, MessageCircle } from "lucide-react";
import { useAuth } from "../context/AuthContext.jsx";
import { useConnections } from "../context/ConnectionsContext.jsx";
import { useToast } from "../context/ToastContext.jsx";
function initialsOf(name) { return (name || "?").split(" ").map((p) => p[0]).join("").slice(0, 2).toUpperCase(); }
export default function Connections() {
  const { user } = useAuth(); const { incomingRequests, outgoingRequests, acceptedConnections, acceptRequest, rejectRequest, cancelRequest } = useConnections(); const toast = useToast();
  const person = (c, key) => key === "from" ? c.fromUser : c.toUser;
  async function act(fn, success) { const r = await fn; if (r.error) toast.error(r.error); else toast.success(success); }
  const row = (c, key, actions) => { const p = person(c, key); if (!p) return null; return <div key={c.id} className="list-row"><Link to={`/dashboard/tutors/${encodeURIComponent(p.email)}`} style={{ display: "flex", alignItems: "center", gap: ".75rem" }}><span className="avatar-fill ember-fill" style={{ width: "2.25rem", height: "2.25rem", fontSize: ".75rem" }}>{initialsOf(p.name || p.fullName)}</span><div><p className="list-row-title">{p.name || p.fullName}</p><p className="list-row-sub">teaches {(p.skills || []).join(", ") || "—"}</p></div></Link><div style={{ display: "flex", gap: ".5rem" }}>{actions(c, p)}</div></div>; };
  return <div><p className="page-eyebrow">Network</p><h1 className="page-title">Connections</h1><p className="page-sub">Connection requests are stored in MongoDB, not browser localStorage.</p><p className="section-title" style={{ marginTop: "2rem" }}>Incoming requests {incomingRequests.length ? `(${incomingRequests.length})` : ""}</p><div style={{ marginTop: ".75rem" }}>{incomingRequests.length ? incomingRequests.map((c) => row(c, "from", (x,p) => <><button className="btn btn-primary btn-sm" onClick={() => act(acceptRequest(x.id), `Connected with ${p.name}`)}><Check size={16}/> Accept</button><button className="btn btn-danger btn-sm" onClick={() => act(rejectRequest(x.id), "Request declined")}><X size={16}/> Reject</button></>)) : <p className="empty-note">No incoming requests right now.</p>}</div><p className="section-title" style={{ marginTop: "2rem" }}>Sent requests {outgoingRequests.length ? `(${outgoingRequests.length})` : ""}</p><div style={{ marginTop: ".75rem" }}>{outgoingRequests.length ? outgoingRequests.map((c) => row(c, "to", (x) => <button className="btn btn-ghost btn-sm" onClick={() => act(cancelRequest(x.id), "Request cancelled")}>Cancel</button>)) : <p className="empty-note">You haven't sent any requests yet.</p>}</div><p className="section-title" style={{ marginTop: "2rem" }}>Your connections {acceptedConnections.length ? `(${acceptedConnections.length})` : ""}</p><div style={{ marginTop: ".75rem" }}>{acceptedConnections.length ? acceptedConnections.map((c) => { const p = c.fromEmail === user?.email ? c.toUser : c.fromUser; return row(c, c.fromEmail === user?.email ? "to" : "from", () => <Link to={`/dashboard/messages/${encodeURIComponent(p.email)}`} className="btn btn-secondary btn-sm"><MessageCircle size={16}/> Message</Link>); }) : <p className="empty-note">No connections yet — head to Explore to find a tutor.</p>}</div></div>;
}
