import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Send, MessageCircle } from "lucide-react";
import { useAuth } from "../context/AuthContext.jsx";
import { useConnections } from "../context/ConnectionsContext.jsx";
import { useToast } from "../context/ToastContext.jsx";
function initialsOf(name) { return (name || "?").split(" ").map((p) => p[0]).join("").slice(0, 2).toUpperCase(); }
function formatTime(iso) { const d = new Date(iso); return d.toDateString() === new Date().toDateString() ? d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : d.toLocaleDateString([], { month: "short", day: "numeric" }); }
export default function Messages() {
  const { email: activeEmail } = useParams(); const navigate = useNavigate(); const { user, findUserByEmail } = useAuth(); const { getConversations, getMessagesFor, sendMessage, getStatusWith } = useConnections(); const toast = useToast();
  const [conversations, setConversations] = useState([]); const [messages, setMessages] = useState([]); const [draft, setDraft] = useState(""); const scrollRef = useRef(null);
  async function loadConversations() { setConversations(await getConversations()); }
  useEffect(() => { loadConversations(); }, [user?.id]);
  const activeConversation = useMemo(() => conversations.find((c) => c.user?.email === activeEmail) || null, [conversations, activeEmail]);
  const activePerson = activeEmail ? findUserByEmail(activeEmail) : null;
  useEffect(() => { if (!activeConversation?.user?._id) { setMessages([]); return; } getMessagesFor(activeConversation.user._id).then(setMessages); }, [activeConversation?.user?._id]);
  useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" }); }, [messages.length]);
  async function handleSend(e) { e.preventDefault(); if (!activeConversation) return; const r = await sendMessage(activeConversation.user._id, draft); if (r.error) return toast.error(r.error); setDraft(""); const next = await getMessagesFor(activeConversation.user._id); setMessages(next); loadConversations(); }
  const status = activeEmail ? getStatusWith(activeEmail).status : null;
  return <div><p className="page-eyebrow">Inbox</p><h1 className="page-title">Messages</h1><p className="page-sub">Messages are stored in MongoDB and available across devices when you use the same account.</p><div className="messages-shell panel" style={{ marginTop: "1.5rem" }}><aside className="conversation-list">{conversations.length === 0 ? <p className="empty-note">No conversations yet — connect with a member first.</p> : conversations.map((c) => { const p = c.user; return <button key={p._id} className={`conversation-item${p.email === activeEmail ? " active" : ""}`} onClick={() => navigate(`/dashboard/messages/${encodeURIComponent(p.email)}`)}><span className="avatar-fill ember-fill" style={{ width: "2.5rem", height: "2.5rem", fontSize: ".8rem" }}>{initialsOf(p.name)}</span><span className="conversation-item-body"><span className="conversation-item-top"><span className="conversation-item-name">{p.name}</span>{c.lastMessage && <span className="conversation-item-time">{formatTime(c.lastMessage.createdAt)}</span>}</span><span className="conversation-item-preview">{c.lastMessage?.message || "Say hello 👋"}</span></span>{c.unreadCount > 0 && <span className="unread-dot">{c.unreadCount}</span>}</button>; })}</aside><section className="chat-area">{!activeEmail ? <div className="chat-empty"><MessageCircle size={32} color="var(--faint-foreground)"/><p className="empty-note">Select a conversation.</p></div> : status !== "accepted" ? <div className="chat-empty"><MessageCircle size={32} color="var(--faint-foreground)"/><p className="empty-note">Messaging is available after the connection is accepted.</p></div> : <><div className="chat-header"><div className="avatar-fill ember-fill" style={{ width: "2.5rem", height: "2.5rem" }}>{initialsOf(activePerson?.fullName || activeConversation?.user?.name)}</div><div><p style={{ fontWeight: 600 }}>{activePerson?.fullName || activeConversation?.user?.name}</p><p className="list-row-sub">SkillSwap member</p></div></div><div className="chat-messages" ref={scrollRef}>{messages.length === 0 ? <p className="empty-note">No messages yet. Say hello 👋</p> : messages.map((m) => { const mine = (m.sender?._id || m.sender) === user?.id; return <div key={m._id} className={`chat-bubble ${mine ? "mine" : "theirs"}`}><p>{m.message}</p><span>{formatTime(m.createdAt)}</span></div>; })}</div><form className="chat-compose" onSubmit={handleSend}><input className="field-input" value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Write a message…"/><button className="btn btn-primary" type="submit"><Send size={16}/></button></form></>}</section></div></div>;
}
